// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class GameInfo {
    "name": string;
    "url": string;
    "img": string;

    /** Creates a new GameInfo instance. */
    constructor($$source: Partial<GameInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("img" in $$source)) {
            this["img"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GameInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameInfo($$parsedSource as Partial<GameInfo>);
    }
}

export class LocalGame {
    "name": string;
    "path": string;
    "img": string;

    /** Creates a new LocalGame instance. */
    constructor($$source: Partial<LocalGame> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("img" in $$source)) {
            this["img"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalGame instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalGame($$parsedSource as Partial<LocalGame>);
    }
}
