// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * DeleteGame 刪除游戏
 */
export function DeleteGame(path: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3456616509, path) as any;
    return $resultPromise;
}

/**
 * GetGameInfo 查询游戏详情
 */
export function GetGameInfo(url: string, img: string): Promise<model$0.LocalGame> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4244880322, url, img) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetGameList returns a greeting for the given name
 */
export function GetGameList(name: string): Promise<model$0.GameInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1324902390, name) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetGameListPage 获取游戏分页列表
 */
export function GetGameListPage(page: number): Promise<model$0.GameInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(357928349, page) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * RunGame 运行游戏
 */
export function RunGame(path: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3274937811, path) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = model$0.LocalGame.createFrom;
const $$createType1 = model$0.GameInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
