// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGame(arg1) {
  return window['go']['internal']['App']['DeleteGame'](arg1);
}

export function GetGameInfo(arg1, arg2) {
  return window['go']['internal']['App']['GetGameInfo'](arg1, arg2);
}

export function GetGameList(arg1) {
  return window['go']['internal']['App']['GetGameList'](arg1);
}

export function GetGameListPage(arg1) {
  return window['go']['internal']['App']['GetGameListPage'](arg1);
}

export function RunGame(arg1) {
  return window['go']['internal']['App']['RunGame'](arg1);
}
