// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteGame(arg1:string):Promise<void>;

export function GetGame():Promise<Array<main.localGame>>;

export function GetGameInfo(arg1:string):Promise<main.GameInfo>;

export function GetGameList(arg1:string):Promise<Array<main.GameInfo>>;

export function RunGame(arg1:string):Promise<void>;
