// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function GetGame() {
  return window['go']['main']['App']['GetGame']();
}

export function GetGameInfo(arg1) {
  return window['go']['main']['App']['GetGameInfo'](arg1);
}

export function GetGameList(arg1) {
  return window['go']['main']['App']['GetGameList'](arg1);
}

export function RunGame(arg1) {
  return window['go']['main']['App']['RunGame'](arg1);
}
